version: '3.8'

services:
  webapp:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    volumes:
      - app_data:/app/data
    container_name: responsive-webapp

volumes:
  app_data:
